# DO NOT EDIT THIS FILE

# An implementation of a C-like array in Python. Array cells are all
# initialized as `None` to start.
class FixedSizeArray:
  # Constructor takes the size of the array. Only indexes in the bounds of
  # [0, size) will be valid for use with this array.
  def __init__(self, size):
    if size <= 0:
      raise Exception("size must be greater than zero")
    self.size = size
    self.items = [None]*size

  # Sets the array cell at index `index` to the value of `elem`, overwriting
  # any other value that may have previously been there.
  def set(self, index, elem):
    if (index > self.size - 1) or (index < 0):
      raise Exception("index out of bounds")
    self.items[index] = elem

  # Returns the value written into the array at index `index`, or None if no
  # such value was written
  def get(self, index):
    if (index > self.size - 1) or (index < 0):
      raise Exception("index out of bounds")
    return self.items[index] 
